#pragma once
#define PAGE_TABLE_SIZE_BYTES 64000
#define FRAME_SIZE_BYTES 256
#define PAGE_SIZE_BYTES 256
#define NUMBER_OF_PAGES PAGE_TABLE_SIZE_BYTES/PAGE_SIZE_BYTES
#define MAX_ADDRESS_CHARACTERS_HEX 8
